name: flutter_sxt_ui_plugin
description: flutter_sxt_ui_plugin
version: 2.4.8
homepage: https://szgitlab.kedacom.com/AndroidTechTeam/flutter_sxtapp
publish_to: http://localhost:6453
update_note: fix bug

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 原生里的代码依赖这个plugin
  sxt_flutter_plugin:
    # path: ../kdvline_flutter_plugin
    hosted:
      name: sxt_flutter_plugin
      url: http://10.67.9.31:6453
    version: 0.12.9

  contact_sdk_flutter:
    #    path: ../contact_sdk_flutter
    hosted:
      name: contact_sdk_flutter
      url: http://10.67.9.31:6453
    version: 0.1.1

  contact_ui_flutter:
    #  path: ../contact_ui_flutter
    hosted:
      name: contact_ui_flutter
      url: http://10.67.9.31:6453
    version: 0.3.7

  flutter_imagepicker_plugin:
    hosted:
      name: flutter_imagepicker_plugin
      url: http://10.67.9.31:6453
    version: 0.2.0

  kd_flutter_map:
    hosted:
      name: kd_flutter_map
      url: http://10.67.9.31:6453
    version: 0.6.2

  flutter_ringtone_player: ^3.1.0
  fluttertoast: ^8.0.3
  flutter_slidable: ^0.6.0
  permission_handler: ^6.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.5
  flutter_bloc: ^7.1.0
  image_picker: ^0.7.4
  video_player: ^2.1.10
  cached_network_image: ^3.0.0
  camera: ^0.8.1+3
  flutter_easyrefresh: ^2.2.1
  flutter_spinkit: ^5.0.0
  just_audio: ^0.9.2
  url_launcher: ^6.0.3
  open_file: ^3.2.0
  flutter_sound: ^8.1.1
  path_provider: ^2.0.1
  extended_text: ^7.0.0
  connectivity: ^3.0.4
  sprintf: ^6.0.0
  intl: ^0.17.0
  logger: ^1.0.0
  meta: ^1.3.0
  flutter_swipe_action_cell: ^2.1.0
  loading_indicator: ^2.0.1
  device_information: ^0.0.4
  file_picker: ^4.0.1
  dartx: ^0.7.1
  vibration: ^1.7.4-nullsafety.0
  package_info_plus: ^1.0.6
  flutter_easyloading: ^3.0.3
  extended_image: ^4.1.0
  syncfusion_flutter_datepicker: ^19.2.62
  flutter_sticky_header: ^0.6.0
  filesize: ^2.0.1
  extended_text_library: ^7.0.0
  dio: ^4.0.0
  json_annotation: ^4.1.0
  event_bus: ^2.0.0
  rxdart: ^0.27.2
  bloc: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  yaml: ^3.1.0
  http: ^0.13.3
  tar: ^0.5.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.kedacom.flutter_sxt_ui_plugin
        pluginClass: FlutterSxtUIPlugin
      ios:
        pluginClass: FlutterSxtUiPlugin

  assets:
    - images/
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
